#!/bin/bash
#
# tasmotaread
# MIT License Copyright (c) 2022 dr-ni
# https://github.com/dr-ni/tasmotaread
#
# A simple bash command-line tool for direct tasmota smart-meter requests.
#
# Requirements: curl and jq must be installed.
#
#
host=$1

# option check
if [ $# -lt 1 ]
then
  echo "Usage: $0 <host>"
  exit 1
fi
# curl http://$host/cm?cmnd=POWER+TOGGLE

for i in 1 2 3
do
  out=$(curl -s http://$host/cm?cmnd=STATUS+8 | jq .)
  if [ "$out" != "" ]
  then
    echo "$out"
    exit 0
  fi
  sleep 3
done
echo "Error: connection to $host failed"
exit 1
