#!/bin/bash
#
# tasmotaread
# MIT License Copyright (c) 2022 dr-ni
# https://github.com/dr-ni/tasmotaread
#
# A simple bash command-line tool for direct tasmota smart-meter requests.
#
# Requirements: curl and jq must be installed.
#
#
host=$1

# option check
if [ $# -lt 1 ]
then
  echo "Usage: $0 <host>"
  exit 1
fi
# curl http://$host/cm?cmnd=POWER+TOGGLE
out=$(curl -s http://$host/cm?cmnd=STATUS+8 | jq)
if [ "$out" = "" ]
then
  sleep 3
  out=$(curl -s http://$host/cm?cmnd=STATUS+8 | jq)
fi
if [ "$out" = "" ]
then
  sleep 3
  out=$(curl -s http://$host/cm?cmnd=STATUS+8 | jq)
fi
if [ "$out" = "" ]
then
  sleep 3
  out=$(curl -s http://$host/cm?cmnd=STATUS+8 | jq)
fi
[ "$out" = "" ] || echo "$out"
